#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

try {
	// Detect CI environments — skip generation
	if (process.env.CI || process.env.GITHUB_ACTIONS) {
		console.log("[devcontainer-config] CI detected, skipping devcontainer.json generation");
		process.exit(0);
	}

	// Go up from scripts/ → package root → @king-studios-rbx/ → node_modules/ → project root
	const projectRoot = path.resolve(__dirname, "..", "..", "..", "..");

	// Sanity check: make sure we're actually inside node_modules
	const expectedNodeModules = path.resolve(__dirname, "..", "..", "..");
	if (path.basename(expectedNodeModules) !== "node_modules") {
		// We're not inside node_modules (e.g. running from the package itself during development)
		console.log("[devcontainer-config] Not inside node_modules, skipping generation");
		process.exit(0);
	}

	// Load base config
	const baseConfigPath = path.resolve(__dirname, "..", "devcontainer-base.json");
	const baseConfig = JSON.parse(fs.readFileSync(baseConfigPath, "utf8"));

	// Set paths for consuming repo
	baseConfig.initializeCommand = "bun install || true";
	baseConfig.build = {
		dockerfile: "../node_modules/@king-studios-rbx/devcontainer-config/docker/Dockerfile",
		context: "..",
	};

	// Ensure .devcontainer directory exists
	const devcontainerDir = path.join(projectRoot, ".devcontainer");
	if (!fs.existsSync(devcontainerDir)) {
		fs.mkdirSync(devcontainerDir, { recursive: true });
	}

	const targetPath = path.join(devcontainerDir, "devcontainer.json");

	// Write with header comments
	const content =
		"// Auto-generated by @king-studios-rbx/devcontainer-config\n" +
		"// Do not edit manually \u2014 update the devcontainer-config package instead\n" +
		JSON.stringify(baseConfig, null, "\t") +
		"\n";

	fs.writeFileSync(targetPath, content);
	console.log("[devcontainer-config] Generated .devcontainer/devcontainer.json");
} catch (err) {
	// Fail gracefully — don't break installs if something goes wrong
	console.warn("[devcontainer-config] Warning: could not generate devcontainer.json:", err.message);
}
