#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

try {
	// Detect CI environments — skip generation
	if (process.env.CI || process.env.GITHUB_ACTIONS) {
		console.log("[devcontainer-config] CI detected, skipping devcontainer.json generation");
		process.exit(0);
	}

	// Find the project root by walking up from the real script location
	// to find the first directory that contains a package.json (that isn't ours)
	// This handles both npm/yarn (flat node_modules) and bun (.bun symlink layout)
	function findProjectRoot() {
		// Strategy 1: Look for node_modules in ancestors and go up one more
		let dir = __dirname;
		for (let i = 0; i < 20; i++) {
			const parent = path.dirname(dir);
			if (parent === dir) break; // hit filesystem root

			// Check if this directory has a node_modules and a package.json
			// and is NOT our package (i.e., not devcontainer-config)
			const pkgPath = path.join(parent, "package.json");
			const nmPath = path.join(parent, "node_modules");
			if (fs.existsSync(pkgPath) && fs.existsSync(nmPath)) {
				try {
					const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
					if (pkg.name !== "@king-studios-rbx/devcontainer-config") {
						return parent;
					}
				} catch (_) {
					// ignore parse errors
				}
			}
			dir = parent;
		}

		// Strategy 2: Use INIT_CWD if available (set by npm/yarn/bun during install)
		if (process.env.INIT_CWD) {
			return process.env.INIT_CWD;
		}

		return null;
	}

	const projectRoot = findProjectRoot();
	if (!projectRoot) {
		console.log("[devcontainer-config] Could not determine project root, skipping generation");
		process.exit(0);
	}

	// Load base config — find it relative to the symlink or real path
	let baseConfigPath = path.resolve(__dirname, "..", "devcontainer-base.json");
	if (!fs.existsSync(baseConfigPath)) {
		// Try via the project's node_modules (handles bun symlinks)
		baseConfigPath = path.join(projectRoot, "node_modules", "@king-studios-rbx", "devcontainer-config", "devcontainer-base.json");
	}
	if (!fs.existsSync(baseConfigPath)) {
		console.warn("[devcontainer-config] Could not find devcontainer-base.json, skipping");
		process.exit(0);
	}

	const baseConfig = JSON.parse(fs.readFileSync(baseConfigPath, "utf8"));

	// Set paths for consuming repo
	baseConfig.initializeCommand = "bun install || true";
	baseConfig.build = {
		dockerfile: "../node_modules/@king-studios-rbx/devcontainer-config/docker/Dockerfile",
		context: "..",
	};

	// Ensure .devcontainer directory exists
	const devcontainerDir = path.join(projectRoot, ".devcontainer");
	if (!fs.existsSync(devcontainerDir)) {
		fs.mkdirSync(devcontainerDir, { recursive: true });
	}

	const targetPath = path.join(devcontainerDir, "devcontainer.json");

	// Write with header comments
	const content =
		"// Auto-generated by @king-studios-rbx/devcontainer-config\n" +
		"// Do not edit manually \u2014 update the devcontainer-config package instead\n" +
		JSON.stringify(baseConfig, null, "\t") +
		"\n";

	fs.writeFileSync(targetPath, content);
	console.log("[devcontainer-config] Generated .devcontainer/devcontainer.json");
} catch (err) {
	// Fail gracefully — don't break installs if something goes wrong
	console.warn("[devcontainer-config] Warning: could not generate devcontainer.json:", err.message);
}
